# -*- org-export-babel-evaluate: nil -*-
#+TAGS: item, tnfsh
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/muse.css" />

#+TITLE: 2020a Items
A:361:1:1,B:353:1:2,C:360:1:3,D:357:1:4,E:356:1:5

* 2023119
** A
QA:399:1:1,
A:7:1:2,
A:12:1:2,
A:18:1:2,
B:104:1:3,
B:105:1:3,
C:8:1:4,
C:13:1:4,
C:19:1:4,
E:390:1:5,
E:391:1:5,
E:392:1:5,
E:393:1:5,
F:256:1:6,
F:257:1:6,
F:314:1:6,
F:315:1:6,
B1:114:1:7,
B1:115:1:7,
B1:116:1:7,
B1:117:1:7,
B2:40:1:8,
B2:41:1:8,
B3:192:1:9,
B3:193:1:9,
B4:201:1:10,
B4:202:1:10
** B
** C
** D
** E
** B1
** B2

** A: 數值運算
- 58 世界上最遙遠的距離
- 59 Falling from cloud
- 153 Oh Heron
** B: 條件判斷
- 339. 1[條件判斷] 鮭魚與龍蝦可以兼得
- 340. [條件判斷] 超級刮刮樂
- 341. [條件判斷] 不知今夕是何夕
- 61. [if/else]BetaCome
- 62. [if/else]棒打老虎雞吃蟲
- 247. [2019-投稿-A]剪刀石頭布
** C: if: 簡單計算
- 155. [2018AM]有一種檸檬，叫做蕚羊的檸檬
- 156. [2018AM]有一種選舉叫做智力測驗
- 310. [2020AM]可憐哪
** D: for+數列
- 101. [2017AF-A]故有無相生，音聲相和
- 102. [2017AF-A]當蝴蝶在南半球拍了兩下翅膀，牠就會稍微飛高一點點
- 103. [2017AF-A]無心無我，故無私；無德無良，故無名
- 309. [2020AM]維尼數列
** E: for+if+sum
- 107. [for] 誰能想的到，這名16歲少女，在四年前，只是一名12歲的小丫頭
- 108. [for] 當一個便當吃不飽時.你可以吃兩個
- 109. [for] 敗家的理由
** B1
- 192. [2019BM-String]人工智障計算機之一
- 336. [APCS] 砍樹 (202001)
- 337. [APCS] 基地台 (201703)
** B2
- 312. [APCS] 秘密差簡單版
- 313. [APCS] 籃球比賽 (201906)
** B3 while/while, while/for
- Bonus3:125:1:8,
- Bonus3:126:1:8
** B4 字元陣列
- B1:21:1:6,
- B1:186:1:6,
- B1:188:1:6,
** B5
- 125. 爬樓梯有益身心健康
- 31. [2019BF-Bonus]老師的逆襲
- 51. [2017AM-BONUS]走樓梯好費力

* 2022 python免修鑑定
** A:233:1:1
356. [Python-3][loop][type][error]態度的重要性
** B:235:1:2,
365. [Python][2021上][期中][loop][string]B. 密碼好難記
** C:281:1:3,
368. [Python][2021上][期中][loop][list]D. Z-transform
** D:113:1:4,
394. [Python][2021上][期末][data]你同意我不同意之公投開票
** E:312:1:5
392. [Python][2021上][期末][while]最小費序

* 2020下學期

* 重補修

1:318:1:1,
2:319:1:2,
3:320:1:3,
4:306:1:4,
5:317:1:5,
6:321:1:6,
7:327:1:7,
8:324:1:8,
9:322:1:9,
10:323:1:10,
11:307:1:11,
12:325:1:12,
13:326:1:13,
14:328:1:14,
15:329:1:15,
16:330:1:16,
17:308:1:17,
18:331:1:18,
19:332:1:19,
20:333:1:20

234 	[2019AM-A] 最簡單問題??  if-elseif

325. [條件判斷] 桃園三結義  if
101.
226 	成績等第 , if-elseif

Q1:62:1:1, [if/else]棒打老虎雞吃蟲

308 	[迴圈] 3 的倍數  for+if+count

[2017AF-A]故有無相生，音聲相和 for+sum
* 2020
Q1:247:1:1,
Q2:215:1:2,
Q2:237:1:2,
Q2:239:1:2,
Q3:23:1:3,
Q3:281:1:3,
Q3:286:1:3,
Q4:55:1:4,
B1:231:1:5,
B1:232:1:5,
B1:233:1:5,
B2:240:1:6,
B2:241:1:6,
B2:242:1:6
* 今年 119
Bonus1:21:1:6,
Bonus1:185:1:6,
Bonus1:186:1:6,
Bonus2:187:1:7,
Bonus2:188:1:7,
Bonus3:125:1:8,
Bonus3:126:1:8

* 可憐哪

#+BEGIN_SRC markdown
# 「**可憐哪**」小辭典：高雄市長韓國瑜參加總統大選辯論會，《中央社》總編輯提問總統候選人，面對中國大陸對台灣分化、統戰以及滲透，如何建立良好的兩岸關係與維護主權？韓國瑜狂言嗆回：「親愛的《中央社》總編輯，你自己的問題都已經把台灣狹窄化，可憐哪～」
# 知名社交網站 twitbook 眼見人氣王名言錄又多一金句，很快的就將此金句套用在網路平台中，在「讚」、「倒讚」之外又加入「可憐哪」tag功能，該tag的規則如下：
  - 所有tag的發佈由poor value來決定
  - 如果某人的發文持續無人按讚，每經過1小時poor value自動+1
  - 當無人按讚時數超過24小時，每經1小時poor value自動+2
  - 當無人按讚時數超過3*24小時，每經1小時poor value自動+3
  - 當無人按讚時數超過7*24小時，每經1小時poor value自動+5
  而該PO文的tag種類則依poo value而有所差異：
  - poor value未超過24: tag顯示 Poor~~
  - poor value未超過60: tag顯示 Poor You!
  - poor value未超過100: tag顯示 Pathetic!!
  - poor value未超過200: tag顯示 Ko lan na~~~
  - poor value超過500: tag顯示 Nonsense post!!!
#+END_SRC
#+begin_src cpp -r -n :results output :exports both
#include <iostream>
using namespace std;
int main() {
    int n;
    cin >> n;
    int pv = 0;
    if (n <= 24) {
        pv = n;
    } else if (n <= 3*24) {
        pv = 24 + (n-24)*2;
    } else if (n <= 7*24) {
        pv = 24 + 2*24*2 + (n-3*24)*3;
    } else {
        pv = 24 + 2*24*2 + 4*24*3 + (n-7*24)*5;
    }
    if (pv <= 24) {
        cout << "Poor~~\n";
    } else if (pv <= 60) {
        cout << "Poor You!\n";
    } else if (pv <= 100) {
        cout << "Pathetic!!\n";
    } else if (pv <= 200) {
        cout << "Ko lan na~~~\n";
    } else {
        cout << "Nonsense post!!!!\n";
    }
}
#+end_src

#+RESULTS:
: 4068
: Nonsense post!!!!

* 2022上學期期中考(119)
** D: for+數列
- 102. [2017AF-A]當蝴蝶在南半球拍了兩下翅膀，牠就會稍微飛高一點點
- 309. [2020AM]維尼數列
** A: for-if-sum
- 118. [2017AF-Bonus]盗墓筆記

** C: if: 簡單計算
- 155. [2018AM]有一種檸檬，叫做蕚羊的檸檬

** E: for+if+sum
- 107. [for] 誰能想的到，這名16歲少女，在四年前，只是一名12歲的小丫頭
- 109. [for] 敗家的理由
** B: 條件判斷
- 156. [2018AM]有一種選舉叫做智力測驗
** Bouns:
- 40. [2019BF-D]韓粉細胞 [Recursive]
- 120. [2017AF-Bonus]打到複雜骨折
- 157. [2018AM-BONUS]Tesseract
- 201. [2019BF-A]打羽毛球囉～～～～
- 402. [2022上][期中][投稿][if][for]我要成為神里家的狗


* 2020上學期期中考
** A: 數值運算
- 58 世界上最遙遠的距離
- 59 Falling from cloud
- 153 Oh Heron
** B: 條件判斷
- 61. [if/else]BetaCome
- 62. [if/else]棒打老虎雞吃蟲
- 247. [2019-投稿-A]剪刀石頭布
- 156. [2018AM]有一種選舉叫做智力測驗
** C: if: 簡單計算
- 55. 快樂天堂
- 56. 血汗工廠
- 155. [2018AM]有一種檸檬，叫做蕚羊的檸檬
- 310. [2020AM]可憐哪
** D: for+數列
- 101. [2017AF-A]故有無相生，音聲相和
- 102. [2017AF-A]當蝴蝶在南半球拍了兩下翅膀，牠就會稍微飛高一點點
- 103. [2017AF-A]無心無我，故無私；無德無良，故無名
- 309. [2020AM]維尼數列
** E: for+if+sum
- 107. [for] 誰能想的到，這名16歲少女，在四年前，只是一名12歲的小丫頭
- 108. [for] 當一個便當吃不飽時.你可以吃兩個
- 109. [for] 敗家的理由
** Bouns:
- 157. [2018AM-BONUS]Tesseract
- 248. [2019-投稿-A]+1
- 251. [2019-投稿-A]兒時記趣
- 252. [2019-投稿-A]奇怪ㄟ
- 253. [2019-投稿-A]期中考之相互踐踏

* 一路衝到掛

* 我們的訴求是開冷氣、開電燈
國民黨立委今（6月28日）突襲，破門進入立法院議場，要求總統蔡英文撤換陳菊，揚言若不撤換，就不撤場，並且要求開冷氣、電燈。

包括國民黨團總召林為洲、書記長蔣萬安等約20位同黨立委占據了立法院議場，在發言台上噴上「監委酬庸，拒絕背書」字樣。林為洲受訪表示，占據議場沒有時間限制，越久越好，最好是三天三夜，並要求開電燈、開冷氣，這樣議場內的非藍委就會撤場。

對此，曾參與太陽花學運占領立法院的民進黨立委賴品妤在臉書發文表示，「大家不要再TAG我技術指導了！」也要大家不要問她在議場怎麼洗澡，「不要問！你會怕！」網友紛紛留言回應，「我以為是趁機不洗澡不洗頭」、「不要教他們怎麼接電」、「太陽花前輩快教教這些新手，立院露營須知。不然這些KMT實在演的很不像……看得很難過。」

好了，為了日後再發生如此丟臉的事件，身為KMT堅定支持者的老師打算幫幫這些脆弱的老藍人，好讓他們...

* 我一瞬間想到了我 1 歲 6 個月大的女兒

* 鐵釘才是王道

* 題庫
** 管你三七二十一 :Easy:for:if:sum:
輸入一個整數 n
求出從 1 ~ n 所有可以被 3 整除及又可以被 7 整除所有 的數字的總和的程式。
#+begin_src python -r -n :results output :exports both
n = 333
sum = 0
for i in range(n+1):
    if i % 3 == 0 and i % 7 == 0:
        sum = sum + i
print(sum)
#+end_src

#+RESULTS:
: 2520

** 天外奇雞 :Easy:for:if:sum:
輸入一個整數 n
計算從 1 到 n 的整數中，所有 奇數 的相乘積並印出。
#+begin_src python -r -n :results output :exports both
n = 11
p = 1
for i in range(1, n+1, 2):
    p = p * i
print(p)
#+end_src

#+RESULTS:
: 10395

** nn多項式 :Easy:for:if:sum:
輸入一個整數 n
求出多項式(1+2)+(2+4)+(3+6)+...+( n+2*n )的和。
#+begin_src python -r -n :results output :exports both
n = 15
sum = 0
for i in range(n+1):
    sum = sum + i + 2*i
print(sum)
#+end_src

#+RESULTS:
: 360

** 買房好難 :Medium:for:if:sum:
輸入一個整數 n
某人在銀行存入$15000，年利率是 4%，如果每年的利息都繼續存入銀行， 請計算在 n 年後，本金加利息一共有多少錢。你可以使用下列公式來計算: 第 n 年底存款總額 = 本金*(1+年利率)^n。
基於現行貨幣制度，只計算到個位數，小數點一律四捨五入。
#+begin_src python -r -n :results output :exports both
n = 50
b = 15000
p = 0.04
t = 1
for i in range(n):
    t = t * ( 1 + p )
print(int(round(b*t, 0)))
#+end_src

#+RESULTS:
: 106600

** 買大/買小 :Easy:string:
請設計一 python 程式，輸入一個字串(text)，將此字串第一個字母改成大寫，其餘字母改成小寫。
#+begin_src python -r -n :results output :exports both
s = 'cOMpUtR'
print(s.lower().capitalize())
#+end_src

#+RESULTS:
: Computr

** 蝸牛老師的點名單 :Medium:string:
繼第一堂課之後同學們因為太無聊了，開始在他們的名字之間空格改成各種不同的字串，例如" and "(不含引號)，假設有兩位同學名字分別是"apple"及"banana"則他們會把點名單寫成"apple and banana"(不含引號)，蝸牛老師很頭痛，希望你幫他寫一個程式把大家的名字分成一行一行的。
#+begin_src python -r -n :results output :exports both
linkStr = 'and'
inputStr = 'appleandbanana'
for item in inputStr.replace(linkStr,' ').split():
    print(item)
#+end_src

#+RESULTS:
: apple
: banana

** Benson打比賽 :for:if:Hard:
Benson眾所皆知是一個電神
每天都要打一些比賽，這些比賽都佔他一天$$\frac{a}{b}$$的時間
最近比賽越來越多，他感覺到時間不夠用
但是他也不清楚這些比賽到底哪個占多少時間
所以他打算把這些比賽所佔的時間轉換成連比例方便看出大小關係
現在給你一些比賽的時間，請你求出一最小正分數$$\frac{p}{q}$$
使得這些比賽時間乘上$$\frac{p}{q}$$都會是正整數
#+begin_src python -r -n :results output :exports both
#!/usr/bin/env python3
def gcd(a, b):
    while a != 0:
        a = a % b
        b = b - a
    return b

n = int(input())
fs = 1
fm = 1
for i in range(n):
    str = input().split()
    s = int(str[0])
    m = int(str[1])
    g = gcd(s, m)
    if g != 1:
        s = s // g
        m = m // g
    fs = gcd(fs, s)
    fm = int(fm * m / gcd(fm, m))
    g = gcd(fs, fm)

print(fm // g, fs // g)
#+end_src

** nn乘法表 :for-for: :for:Medium:
輸入1，輸出
1*1=1
輸入3，輸出
1*1=1
2*1=2 2*2=4
3*1=3 3*2=6 3*3=9
輸入n，輸出結果(每個式子後都有一個空白)
#+begin_src python -r -n :results output :exports both
n = 5
for i in range(1, n):
    for j in range(1, i+1):
        print("%d*%d=%d" %(i, j, i*j), end=' ')
    print()
#+end_src

#+RESULTS:
: 1*1=1
: 2*1=2 2*2=4
: 3*1=3 3*2=6 3*3=9
: 4*1=4 4*2=8 4*3=12 4*4=16


** 數列質幾何？ :prime:Easy:
輸入m, n，輸出介於m至n(包含m,n)的連續整數中共有多少個質數？
#+begin_src python -r -n :results output :exports both
import math
m = 101
n = 200

def isPrime(i):
    for p in range(2, int(math.sqrt(i))+1):
        if i % p == 0:
            return False
    else:
        return True

countP = 0
for i in range(m, n+1):
    if isPrime(i):
        countP += 1

print(countP)

#+end_src

#+RESULTS:
: False
: 21

** Reduce number :Hard:prime:while:
質因數分解
#+begin_src python -r -n :results output :exports both
n = 1026
i = 2
sList = []
while n != 1:
    while i <= n:
        if n % i == 0:
            sList.append(i)
            n = n // i
            break
        else:
            i += 1
print("*".join(map(str,sList)))
#+end_src

#+RESULTS:
: 2*3*3*3*19

** String caculator :Medium:string:for:if:
輸入一行字符，分別統計出其中英文字母、空格、數字和其它字符的個數。
#+begin_src python -r -n :results output :exports both
str = '123runoobc  kdf235*(dfl'
letters = 0
space = 0
digit = 0
others = 0
for c in str:
    if c.isalpha():
        letters += 1
    elif c.isspace():
        space += 1
    elif c.isdigit():
        digit += 1
    else:
        others += 1
print('char = %d' %(letters))
print('space = %d' %(space))
print('digit = %d' %(digit))
print('other = %d' %(others))
#+end_src

#+RESULTS:
: char = 13
: space = 2
: digit = 6
: other = 2

** 保安，可以讓人這樣加了又加加了又加的嗎??
求s=a+aa+aaa+aaaa+aa...a的值，其中a是一個數字。例如2+22+222+2222+22222(此時共有5個數相加)，幾個數相加由鍵盤控制。
#+begin_src python -r -n :results output :exports both
n = 4
a = 4
nList = [a]
for i in range(4-1):
    a = a * 10 + nList[0]
    nList.append(a)
print(sum(nList))
#+end_src

#+RESULTS:
: [4, 44, 444, 4444]
: 4936

** 自由落體 :Medium:for:if:
一球從100米高度自由落下，每次落地後反跳回原高度的一半；再落下，求它在第10次落地時，共經過多少米？第10次反彈多高？
#+begin_src python -r -n :results output :exports both
height = 100
times = 10

total = height
height = height / 2
for i in range(times-1):
    total = total + height*2
    height = height / 2

print(total,height)
#+end_src

#+RESULTS:
: 299.609375 0.09765625

** 分數數列 :Easy:for:sum:
有一分數序列：2/1，3/2，5/3，8/5，13/8，21/13...求出這個數列的前20項之和。
#+begin_src python -r -n :results output :exports both
n = 20
s = 2.0
m = 1.0
sum = 0
for i in range(n):
    sum += s/m
    s, m = s+m, s

print(sum)

#+end_src

#+RESULTS:
: 32.66026079864164
#+begin_src cpp -r -n :results output :exports both
#include <iostream>
using namespace std;
int main() {
    long int n = 4;
    long int s = 2;
    long int m = 1;
    for (int i = 0; i < n; i++) {
        cout << s << "/" << m << endl;
        long int tmp = s+m;
        m = s;
        s = tmp;
    }
}
#+end_src

#+RESULTS:
: 2/1
: 3/2
: 5/3
: 8/5

** m!~n!和, 10!+11!+....+20! :Medium:for:
#+begin_src python -r -n :results output :exports both
m = 10
n = 20
t = 1
summ = 0
sumn = 0
for i in range(1, n+1):
    t *= i
    sumn += t
    if i < m:
        summ += t
print(summ)
print(sumn)
print(sumn - summ)
#+end_src

#+RESULTS:
: 409113
: 2561327494111820313
: 2561327494111411200
#+begin_src python -r -n :results output :exports both
m = 10
n = 20
t = 1
sum = 0
for i in range(1, n+1):
    t *= i
    if i >= m:
        sum = sum + t
print(sum)
#+end_src

#+RESULTS:
: 2561327494111411200

** common elements :Hard:list:for:
小潘跟小花都有很多個正整數，自己的數不會有重覆出現的，而且都是遞增排列。
現在她們想要知道，兩個人的數有幾個重覆的呢？
*** 輸入說明 ：
第一行有兩個數字n,m。 (1<=n<=100,1<=m<=10000)
接著共有n筆測資，每筆測資共有兩行，分別代表兩個人擁有的數，每行共有m個數。
所有數字都不大於231-1。
*** 輸出說明 ：
每筆測資請輸出一個數字，
代表兩個人的數有幾個重覆的。
*** 範例輸入 ：
2 6
1 5 6 8 9 13
3 4 5 7 8 11
4 6 7 14 16 23
6 9 12 13 16 23
*** 範例輸出 ：
2
3
#+begin_src python -r -n :results output :exports both
while True:
    try:
        n = list(map(int,input().split()))[0]
        for i in range(n):
            set1 = set(input().split())
            set2 = set(input().split())
            print(len(set1 & set2))
    except EOFError:
        break
#+end_src

** 吞食天地 :Hard:list:
出處 ：  http://zerojudge.tw/ShowProblem?problemid=a693
*** 內容 ：
好餓歐歐歐歐
有 n 個食物在你面前排成一排
每個食物有它的飽足度
你想知道把其中一段通通吃掉會獲得多少飽足度
*** 輸入說明 ：
多組測資以 EOF 結束
每組測資開始有兩個正整數 n,m (n,m <= 100000)
接下來一行有 n 個不超過一千的正整數依序代表每個食物的飽足度
接下來 m 行每行有兩個數字 l,r (1 <= l <= r <= n)
代表你想要吃掉第 l 個到第 r 個食物
*** 輸出說明 ：
對每組測資輸出 m 行，代表總飽足度
*** 範例輸入 ：
3 3
1 2 3
1 3
1 2
2 3
*** 範例輸出 ：
6
3
5
#+begin_src python -r -n :results output :exports both
while True:
    try:
        n = int(input().split()[0])
        intList = input().split()
        for i in rang(n):
            checkList = list(map(int, input().split()))
            nStar = checkList[0]
            nEnd = checkList[1]
            print(sum(checkList[nStar:nEnd+1]))
    except EOFError:
        break
#+end_src
#+begin_src python -r -n :results output :exports both
list = [1, 2, 3, 4, 5]
print(sum(list[2:4]))
#+end_src

#+RESULTS:
: 7

** 最大和 :Hard:list:
*** 問題描述
給定 N 群數字,每群都恰有 M 個正整數。若從每群數字中各選擇一個數字 (假設第
i 群所選出數字為 ti ),將所選出的 N 個數字加總即可得總和 S = t1+t2+...+tN。請寫程
式計算 S 的最大值 (最大總和),並判斷各群所選出的數字是否可以整除 S。
*** 輸入格式
第一行有二個正整數 N 和 M, 1≦ N ≦ 20,1≦ M ≦ 20。
接下來的 N 行,每一行各有 M 個正整數 xi ,代表一群整數,數字與數字間有一個空
格,且 1≦ i ≦M,以及 1≦ xi ≦256。
*** 輸出格式
第一行輸出最大總和 S。
第二行按照被選擇數字所屬群的順序,輸出可以整除 S 的被選擇數字,數字與數字間
以一個空格隔開,最後一個數字後無空白;若 N 個被選擇數字都不能整除 S,就輸出-1。
*** 範例一：輸入
3 2
1 5
6 4
1 1
*** 範例一：正確輸出
12
6 1
*** 範例二：輸入
4 3
6 3 2
2 7 9
4 7 1
9 5 3
*** 範例二:正確輸出
31
-1
#+begin_src python -r -n :results output :exports both
n = int(input().split()[0])
sum = 0
maxList = []
for i in range(n):
    tmp = max(list(map(int,input().split())))
    maxList.append(tmp)
    sum += tmp
print(sum)

found = False
for i in maxList:
    if sum % i == 0:
        print(i, end=' ')
        found = True
        
if found == False:
    print(-1)
     

#+end_src

** 態度的重要性
*** 內容 ：
今天我們如果將a=1,b=2,c=3....以此類推下去，
將單字裏的每個文字依照上面規則轉換成數字再相加起來的話。
知識(KNOWLEDGE)只有96分，
努力(HARDWORK)只有98分，
但態度(ATTITUDE)卻是100分。

風台高中的Norton看到了上面的文章後並不相信，
他想把它們真的加起來看看，
以找到一個字可以反駁這個「態度最重要」的理論
但卻討厭換來換去的過程，
請幫他寫個程式方便他去做運算。

*** 輸入說明 ：
輸入英文單字，大小寫不限，當輸入0的時候就結束程式。
長度最長為200個字。
請參照Sample Input。

*** 輸出說明 ：

輸出將英文單字依照題目的規則轉換成數字後相加的結果，如果中間參雜怪異的符號，請輸出Fail；但是英文字母的大小寫並不會影響結果，也就是說A和a所代表的值是相同
的。請參照Sample Output。
*** 範例輸入 ：

hardwork
KNOWLEDGE
aTtitUdE
C++
0

*** 範例輸出 ：

98
96
100
Fail
*** Code :Medium:Dict:
#+begin_src python -r -n :results output :exports both
chDict = { 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26 }

while True:
    str = input()
    if str == '0':
        break
    if not str.encode('UTF-8').isalpha():
        print('Fail')
    else:
        sum = 0
        for ch in list(str):
            sum += chDict[ch]
        print(sum)
#+end_src

#+RESULTS:

* test
#+begin_src cpp -r -n :results output :exports both
#include <stdio.h>
using nab
mespace std;
int main() {
    printf("格式印出:%7.2f\n", 12.34);
    printf("格式印出:%7.2f\n", 123.1);
    printf("格式印出:%7.2f\n", 34.3434);
    printf("格式印出:%-7.2fLALALA", 34.3434);
}
#+end_src

#+RESULTS:
: 格式印出:  12.34
: 格式印出: 123.10
: 格式印出:  34.34
: 格式印出:34.34  LALALA
